### ISSUE TITLE
Nested syntax highlighting for Go templates inside YAML files

### ISSUE THREAD

**Issue by jimmycuadra** [andrewstuart/vim-kubernetes#9]
I'm not sure if [this line](https://github.com/andrewstuart/vim-kubernetes/blob/c697698ca252edc8bd921604d25a72c778bca4eb/ftdetect/kubeconf.vim#L4) somehow causes Go templates within YAML to be highlighted with some other plugin, but out of the box, setting the filetype to "yaml.gotexttmpl" has no effect compared to just using the filetype "yaml" for me. I was able to the Go templates embedded in YAML to highlight using the following code:

``` viml
function HelmSyntax()
  set filetype=yaml
  unlet b:current_syntax
  syn include @yamlGoTextTmpl syntax/gotexttmpl.vim
  let b:current_syntax = "yaml"
  syn region goTextTmpl start=/{{/ end=/}}/ contains=@gotplLiteral,gotplControl,gotplFunctions,gotplVariable,goTplIdentifier containedin=ALLBUT,goTextTmpl keepend
  hi def link goTextTmpl PreProc
endfunction
augroup helm_syntax
  autocmd!
  autocmd BufRead,BufNewFile */templates/*.yaml,*/templates/*.tpl call HelmSyntax()
augroup END
```

Is there something I'm missing that would make this unnecessary, or would this be a useful addition to vim-kubernetes?

**Comment by andrewstuart** [comment]
Awesome, thank you for this! Just added it.

**Comment by jemag** [comment]
I believe this will not work unless you have https://github.com/fatih/vim-go installed and enabled for yaml filetypes (since it is the one providing the gotexttmpl.vim).

I don't think this should be default since it will error out for most users like so: 
![image](https://user-images.githubusercontent.com/7985687/119268720-3ad4b480-bbc2-11eb-9422-fcdfeaa26018.png)
